### ISSUE TITLE
New LineageOS 17.1 Build, Audio still uses speakers not Earphones when a Headset is plugged in

### ISSUE THREAD

**Issue by ghost** [enesuzun2002/lineageos-ota#10]
I have installed the latest Lineage OS 17.1 Build and the Audio still ignores my wired headset/earphones and still uses Speakers. This appears to come from every audio source, web browser, YouTube, etc. The fix that you have implemented has not actually changed anything and if a fix could be implemented then I would be grateful, because audio on headset does not work.

**Comment by ktzouno** [comment]
Thanks for the effort to port LineageOS 17.1 to the S6 👍 

Additionally to the above problem, I also notice it on phone calls. I tried with multiple Apps, Android Phone, Zoiper, Facebook Messenger and the behavior similar: their Speakerphone icon is either `on` and can't be turned `off`, or can be turned `on` and `off` but nothing really changes, the sound comes out of the Speakerphone.

Connecting a wired-headset doesn't change anything. There is no sound on the headset, only on the Speakerphone.

I'm using the release `LineageOS-10-zero-multitarget-2020-02-28_1703` https://github.com/enesuzun2002/lineageos-ota/releases/tag/lineage-17.1-20200228
