### ISSUE TITLE
may i ask some questions here?

### ISSUE THREAD

**Issue by michapixel** [enesuzun2002/lineageos-ota#13]

**Comment by michapixel** [comment]
I have a TWRP-enabled S6-edge lying next to me. 
At first i tried the latest LineageOS of 14.1 and i managed to enter the setup. But it got hung on trying to update via WIFI (because the servers are not responding i guess, because this part is officially dead ;( )
So i found this project somehow, and it worked like a charm, until ...
i would like to have Play-Store functionality too, does anyone have a good advice of how to sideload GApps or similar?
Is this even possible?

**Comment by steve-todorov** [comment]
Not a place for asking questions but for reporting issues. For questions you can use xda developers and/or the telegraph channel. Anyway - you can download and flash through TWRP [OpenGApps](https://opengapps.org/).
