### ISSUE TITLE
No network on G920W8 (Canadian variant)

### ISSUE THREAD

**Issue by sandmix** [enesuzun2002/lineageos-ota#14]
Hi,
 Updated to this rom from last oficial, baseband version G920W8VLU6DRF,1 sometime can get network, but no data, rolled back to stock stable network and data.
Maybe somone knows what baseband should be use or have fix for this issu.

Thanks

**Comment by SkyyySi** [comment]
I'm having the same issue on my SM-G920F , so this is probably an issue with this build rather than your device!

**Comment by enesuzun2002** [comment]
Please check F.A.Q. in XDA thread there is a workaround for that issue for T-Mobile devices
