### ISSUE TITLE
3 issues with latest lineageos 17 release

### ISSUE THREAD

**Issue by virtualpanna** [enesuzun2002/lineageos-ota#16]
Hi,
first of all, thank you for your releases.

I faced 3 issues with your latest lineageos 17 relase for zeroflteXX

1- selinux is disabled
2- no root is available from lineageOS extras
3- in all the releases I tried your build is signed with a public key (trust alerts shows it)

I hope you can help
thanks again

cheers

**Comment by SkyyySi** [comment]
For root, you have to install magisk via TWRP, the official lineageos team dropped it.

**Comment by enesuzun2002** [comment]
1- Selinux will not be enabled anytime soon because i don't have time to work on it
2- Already answered
3- I will start signig my builds soon
