### ISSUE TITLE
How to upgrade build with TWRP

### ISSUE THREAD

**Issue by AtlasC0R3** [enesuzun2002/lineageos-ota#19]
So, there Is a new build released, and I was unsure how to upgrade it over the build I have. I have tried flashing LineageOS 17.1 over 16 using TWRP and it did upgrade, but it bootlooped until I wiped the device clean and started over. I also went to see the LineageOS update thing and there's nothing. Do I just flash it or do I have to start over?

**Comment by chrispbaker83** [comment]
I had the same issue using TWRP, stuck on the LineageOS boot logo after the dirty flash. I was able to boot by using adb sideload through TWRP.

**Comment by AtlasC0R3** [comment]
Thanks! Seems to have solved the issue.
