### ISSUE TITLE
S6 Edge : G925F - Build  20190614 charging doesn't work / work very bad

### ISSUE THREAD

**Issue by sercatum** [enesuzun2002/lineageos-ota#2]
Hi,
I do report error, maybe you can help.
After update to OS16  20190614 Build (from oreo 7.0 ) charging not work well:
-  wireless charge doesn't work at all.
It just keeps heating telephone and pad, % reported at phone drops

- cable charge work but .... reaaaaaaaalllllly slow. After 20 min it recharge max 3-4 %.
After 5 h battery from 50% went to 95%

**Comment by CrazyFox04** [comment]
Hi,
For me (the same phone), charging work fine.
I think reflash the build may be resolve this problem.
I hope that I resolve your problem.

**Comment by denistry** [comment]
Dear developer!  Sorry for my English, I’m just from Ukraine. The Los16 (Samsung s6) firmware is very good. But there are two problems. The first one is the camera, it shoots terribly. Another problem is that all the videos on the Instagram are of poor quality. You will fix it in the future,  Or are you already doing this firmware?

**Comment by SakiiCode** [comment]
Are you using the 20191014 version? I used it and it didn't have those problems

**Comment by denistry** [comment]
> Вы используете версию 20191014? Я использовал его, и у него не было тех проблем

Yes, I installed the latest release. The camera takes poor photographs, poor image quality, and the shutter is slow.

**Comment by denistry** [comment]
> Вы используете версию 20191014? Я использовал его, и у него не было тех проблем

Maybe you need a patch for the camera?

**Comment by denistry** [comment]
![Screenshot_20191117-000232](https://user-images.githubusercontent.com/57844772/68999794-77896680-08ce-11ea-8408-d4cb37d3c2c1.png)
And the question is, what are these three files after the archive with firmware?

**Comment by SakiiCode** [comment]
They are used for checking the integrity of the archive. Usually you don't need them. Do you have Galaxy S6 or S6 Edge?

**Comment by denistry** [comment]
> Они используются для проверки целостности архива. Обычно они вам не нужны. У вас есть Galaxy S6 или S6 Edge?

Yes,galaxy s6- g920f.

**Comment by SakiiCode** [comment]
~~Then this ROM is not for your model. Choose another one from here: https://forum.xda-developers.com/galaxy-s6/orig-development~~
Edit: it is.

**Comment by enesuzun2002** [comment]
This rom supports G920F model don't give wrong information please. His cable, usb port or charger is broken.
