### ISSUE TITLE
[Bug] Camera freezing Problems Video calls (Whatsapp/Signal)

### ISSUE THREAD

**Issue by ghost** [enesuzun2002/lineageos-ota#28]
Hello,
Thank you for your work and I have found another problem and with many other AOSP roms, that can be used for the Samsung s6 phone. 

The problems are that when the user decides to use a service such as Whatsapp or Signal after 30 minutes or so the camera freezes when they are using the camera to have a video call. I suspected it to be a software issue but now it could be a rom issue. 

Here is the snippet of adb log that I had gotten when I was having a video call, and then the camera froze:

05-29 20:15:29.948  3171 16141 D RefBase : RefBase: Explicit destruction, weak count = 0 (in 0xedffea24)
05-29 20:15:29.948  3171 16141 W RefBase : CallStack::getCurrentInternal not linked, returning null
05-29 20:15:29.948  3171 16141 W RefBase : CallStack::logStackInternal not linked
05-29 20:15:29.952  3171  3546 E HandleImporter: failed to dup fence fd 17229
05-29 20:15:29.952  3171  3546 E CamDevSession@3.2-impl: importRequestImpl: output buffer 0 acquire fence is invalid
05-29 20:15:29.954  3228 16127 E Camera3-Device: Camera 0: sendRequestsBatch: RequestThread: Unable to submit capture request 33622 to HAL device: Function not implemented (-38)
05-29 20:15:29.969 11132 15888 E org.webrtc.Logging: Camera2Session: Error: Camera device has encountered a fatal error.
05-29 20:15:29.970 11132 15888 I org.webrtc.Logging: Camera2Session: Stop internal
05-29 20:15:29.970 11132 15888 I org.webrtc.Logging: SurfaceTextureHelper: stopListening()
05-29 20:15:29.983 11132 15888 E CameraCaptureSession: Session 0: Exception while stopping repeating: 
05-29 20:15:29.983 11132 15888 E CameraCaptureSession: android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error

Here is the entire Log that I had gathered: 
https://github.com/apptester235/Crash-Log/blob/master/Log

If this issue is truly related to the Rom and if it could be fixed then It would be greatly appreciated.

**Comment by szazs89** [comment]
I have similar issues, though with an older ROM (LOS 16.0, ~2020-01-21). I found that using the camera, my S6 gets extremely hot before it freezes.

**Comment by ghost** [comment]
That is another issue this ROM faces, and many other ROMs in fact, they have issues with camera stability and temperature. 

I have been experiencing the same issue in regards to the phone getting warm when I have used other video calling software.

**Comment by enesuzun2002** [comment]
This issue is resolved thanks to @Exhigh's new hex-edited camera blobs
