### ISSUE TITLE
NFC does not enable with latest build

### ISSUE THREAD

**Issue by orpharion** [enesuzun2002/lineageos-ota#3]
NFC does not successfully turn on with release LineageOS-9-zero-multitarget-2019-08-16_1752.
I don't know if it worked before.
I've used logcat and kmsgcat to capture debug logs ([logfile_nfc.txt](https://github.com/enesuzun2002/lineageos-ota/files/4007892/logfile_nfc.txt))
I tried enabling NFC at approximately 17:12.
Notable errors that occure whenever I log:
E/WakeLock(16067): GCM_HB_ALARM release without a matched acquire!
E/KernelUidCpuTimeReader(15085): Failed to read uid_cputime: /proc/uid_cputime/show_uid_stat (No such file or directory)
E/BufferQueueProducer(14665): [com.android.settings/com.android.settings.SubSettings#0] disconnect: not connected (req=1)
E/BufferQueueProducer(14665): [StatusBar#0] disconnect: not connected (req=1)
E/HWC2On1Adapter(14665): setPowerMode: Failed to set power mode on HWC1 (-1)
E/KernelUidCpuTimeReader(15085): Failed to read uid_cputime: /proc/uid_cputime/show_uid_stat (No such file or directory)
Not sure if any of these are related. Happy to provide further info.

**Comment by Timmmy001** [comment]
This is true. NFC will not turn on when the button is pressed, but it will be active with the next restart and can be used.

**Comment by szazs89** [comment]
I think this bug still exists. I had no success with NFC, even after rebooting the device.

**Comment by SakiiCode** [comment]
Works for me on 2020-04-18 build

**Comment by enesuzun2002** [comment]
NFC is fixed on latest builds for both 17.1 and 16.0
