### ISSUE TITLE
Dual SIM problem with Galaxy S6 Duos variant

### ISSUE THREAD

**Issue by ghost** [enesuzun2002/lineageos-ota#31]
It seems the _zerofltexx_ (S6 flat) build doesn't fully support dual SIM initially. This is also the case in the official LOS 14 (Nougat) back then. Although it is partially working sometimes... requires a few reboots to work when powered off, overall, it is pretty much usable.

My device is the [S6 Duos](https://m.gsmarena.com/samsung_galaxy_s6_duos-7377.php) (SM-G920FD) variant, currently running the latest LOS 16 build [20200418](https://github.com/enesuzun2002/lineageos-ota/releases/tag/lineage-16.0-20200418).

**Comment by ghost** [comment]
@enesuzun2002 I don't know if this is specific to my device, but in any case, I would like to help fix this issue. Can you give me some reference to the sources where I could start digging?

**Comment by enesuzun2002** [comment]
Can you provide log's please when this issue happens?

**Comment by ghost** [comment]
From a newly flashed ROM, I've taken a logcat for both working and not working state. I used the Termux app for this process:

- [NOT WORKING STATE LOGCAT](https://pastebin.com/FSf4DQ8D)
- [WORKING STATE LOGCAT](https://pastebin.com/njpg8Xyg)

Additionally, here are some screenshot's of my IMEI goes missing when any SIM isn't detected: 
<ul>
<li><details><summary>NOT WORKING STATE  SCREENSHOTS</summary>

![Screenshot_20200725-024206_Settings](https://user-images.githubusercontent.com/44991669/88428788-20a63a80-ce28-11ea-87b7-ecbb50415a9d.png)

![Screenshot_20200725-024219_Settings](https://user-images.githubusercontent.com/44991669/88428930-5c410480-ce28-11ea-8f83-97ec296654db.png)

![Screenshot_20200725-024227_Settings](https://user-images.githubusercontent.com/44991669/88428946-6531d600-ce28-11ea-95e7-8ffb1b98efce.png)

</details></li>
<li><details><summary>WORKING STATE  SCREENSHOTS</summary>

![Screenshot_20200725-024506_Settings](https://user-images.githubusercontent.com/44991669/88428978-767ae280-ce28-11ea-802d-fceffb85d340.png)

![Screenshot_20200725-024515_Settings](https://user-images.githubusercontent.com/44991669/88428990-7da1f080-ce28-11ea-9525-f9fef156ad9e.png)

![Screenshot_20200725-024525_Settings](https://user-images.githubusercontent.com/44991669/88429001-81ce0e00-ce28-11ea-80f5-f3651b6f07e0.png)

</details></li>
</ul>

**Comment by ghost** [comment]
@enesuzun2002 Just notify me if there's anything I could help you with.
