### ISSUE TITLE
Charging notification light

### ISSUE THREAD

**Issue by LeeGLord** [enesuzun2002/lineageos-ota#33]
Hello Enes. Wonderful ROM. Been using it all this year. Very stable. Great work. One small issue I have noticed is that the charging LED fails to recognise charging at times. This is easily remedied with a reboot but does re-occur after several days. Let me know if anything else is needed to help diagnose this issue. Very much looking forward to a security update. Best regards. Lee

**Comment by enesuzun2002** [comment]
This should be fixed too.
