### ISSUE TITLE
Hotspot non funzionante

### ISSUE THREAD

**Issue by spiderman577** [enesuzun2002/lineageos-ota#40]
Buongiorno, è possibile riparare il problema? Quando faccio Hotspot l icona si accende per pochi secondi e poi si spegne da solo.

https://user-images.githubusercontent.com/113228206/189471260-5217725e-f808-4ccb-b5ae-f1c50be8532e.mp4

**Comment by enesuzun2002** [comment]
Should be fixed on next build so until then i am locking conversation

**Comment by enesuzun2002** [comment]
Fixed
