### ISSUE TITLE
[Errors and Warnings] RILD, libc, com.android.phone

### ISSUE THREAD

**Issue by nsherbina1999** [enesuzun2002/lineageos-ota#6]
```
01-22 16:00:12.216 12175 13533 E RILD    : [G] RX: (M)DISP_CMD (S)DISP_ICON_INFO (T)NOTI l:11 m:90 a:00 [ 01 04 00 00 00 00 FF FF FF FF ]: /v
01-22 16:00:12.217 12175 13533 E RILD    : IpcProtocol41::IpcRxDispIconInfo(): modemType=4: /v
01-22 16:00:12.217 12175 13533 E RILD    : Signal Strength: [4, 16, 99, 16, 200, 16, 200, -1, 0, 2147483647, 255, 2147483647, 2147483647, 2147483647]: /v
01-22 16:00:12.217 12175 12451 E RILD    : GLNET-MGR(3): evt(201): /v
01-22 16:00:12.217 12175 13533 E RILD    : [G] RX: (M)DISP_CMD (S)DISP_RSSI_INFO (T)NOTI l:10 m:91 a:00 [ 59 0C 63 63 00 FF FF FF FF ]: /v
01-22 16:00:12.217 12175 12451 E RILD    : NET-MGR: EVENT_NETWORK_SIGNAL_STRENGTH: /v
01-22 16:00:12.218 12175 12451 E RILD    : OnNetworkSignalStrength() - mSignalBar: 4: /v
01-22 16:00:12.218 12175 13533 E RILD    : ConvertDbmToAsu(): dbm=89, asu=12: /v
01-22 16:00:12.218 12175 12451 E RILD    : IsRegisteredNetworkType(): netType[1]  feature[00] state[0] : /v
01-22 16:00:12.218 12175 13533 E RILD    : IpcRxDispRssiInfo(): signalbar=-1, signal=12: /v
01-22 16:00:12.218 12175 12451 E RILD    : OnUnsolicitedResponse: unsolId: 1009: /v
01-22 16:00:12.218 12175 12451 E RILD    : GLNET-MGR(3): evt(201): /v
01-22 16:00:12.218 12175 12451 E RILD    : NET-MGR: EVENT_NETWORK_SIGNAL_STRENGTH: /v
01-22 16:00:12.218 12175 12451 E RILD    : OnNetworkSignalStrength() - mSignalBar: 4: /v
01-22 16:00:12.218 12175 12451 E RILD    : IsRegisteredNetworkType(): netType[1]  feature[00] state[0] : /v
01-22 16:00:12.218 12175 12451 E RILD    : OnUnsolicitedResponse: unsolId: 1009: /v

```

Also:
`01-22 16:02:58.694 26291 26377 E libc    : The property "ro.build.fingerprint" has a value with length 94 that is too large for __system_property_get()/__system_property_read(); use __system_property_read_callback() instead.: com.alibaba.aliexpresshd:channel`

Found probable fix:
`01-22 16:02:59.913 12638 12656 E KernelUidCpuTimeReader: Failed to read uid_cputime: /proc/uid_cputime/show_uid_stat (No such file or directory): system_server`

(fix) https://git.congatec.com/android/qmx6_kernel/commit/988785de6c79081fca2af0d66ff5e87099cb25a9?view=parallel

Phone errors and warnings:
`01-22 16:03:59.378 12993 12993 D ImsManager: Connector: getImsService: com.android.phone
01-22 16:03:59.379 12993 12993 I ImsManager: Creating ImsService: com.android.phone
01-22 16:03:59.383 12993 12993 W MmTelFeatureConnection: create: binder is null! Slot Id: 0: com.android.phone
01-22 16:03:59.384 12993 12993 E ImsManager: Connector: Retrying getting ImsService...: com.android.phone`

No shutter sound file:
`01-22 17:07:38.478 20833 20833 E SoundPool: error loading /product/media/audio/ui/camera_click.ogg: com.android.camera2`

`01-22 17:07:38.915  5901  6440 E Sensors : Sensor : Meta event: /vendor/bin/hw/android.hardware.sensors@1.0-service`

`01-22 17:07:39.082  5953  6431 E ExynosCamera3: Build Date is (__DATE__) (__TIME__): /system/bin/cameraserver`

`01-22 17:07:39.155  5953  6431 E ExynosCamera3Interface: INFO(HAL3_camera_device_initialize[207]): dual cam_state[0](1): /system/bin/cameraserver`

**Comment by enesuzun2002** [comment]
Most of this logs are nothing that important but still thanks for pointing it out.
